name: Build (branch Main)
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy-dot-com:
    name: Build and Deploy removeunused.com
    runs-on: ubuntu-latest
    needs:
      - static
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install Dependencies
        run: |
          pnpm i --frozen-lockfile
      - name: Build
        run: |
          pnpx nx build davidturissini-com
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy packages/davidturissini-com/dist --project-name=davidturissini-blog
